Project1:对文件diabetes.csv中的数据进行处理，将文件夹pima-diabetes放在E：盘的input文件夹下

In [5]:
from pandas import *
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib notebook
from scipy.stats import mode

import os
print(os.listdir("D:"))

['.ipynb_checkpoints', 'answer1-python-data-pre-processing-handy-tips.ipynb', 'pima-diabetes']

In [6]:
################################读入diabetes.csv文件到diabetes################################### 
diabetes = pd.read_csv('D:/pycharm/pima-diabetes/diabetes.csv')
################################读入diabetes.csv文件到diabetes###################################

In [7]:
################################显示diabetes的前5行################################### 
diabetes.head(5)
################################显示diabetes的前5行###################################

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

Check for Summary Statistics

In [8]:
################################显示diabetes的详细信息，包括样本数、均值、方差等等################################## 
diabetes.describe()
################################显示diabetes的详细信息，包括样本数、均值、方差等等##################################

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [9]:
################################显示diabetes中Outcome列中每种值出现的次数################################## 
diabetes["Outcome"].value_counts()
################################显示diabetes中Outcome列中每种值出现的次数##################################

0    500
1    268
Name: Outcome, dtype: int64

### Check missing values

In [10]:
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [11]:
################################显示diabetes中所有列的标题名################################## 
diabetes.columns
################################显示diabetes中所有列的标题名##################################

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [12]:
################################显示diabetes中所有列的值里面为0的个数################################## 
print((diabetes[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']] == 0).sum())
################################显示diabetes中所有列的值里面为0的个数##################################

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
dtype: int64

In [13]:
################################将diabetes中所有列的值中为0的值替换为NaN################################## 
diabetes.loc[:,['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI']] = diabetes[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI']].replace(0, np.NaN)

################################将diabetes中所有列的值中为0的值替换为NaN################################## 
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1.0,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8.0,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,NaN,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [14]:
################################统计diabetes中所有列的值中为null的个数################################## 
diabetes.isnull().sum()
################################统计diabetes中所有列的值中为null的个数##################################

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

## Dealing with missing values

## A. Drop rows having NaN

In [15]:
print("Size before dropping NaN rows",diabetes.shape,"\n")

################################将diabetes中包含NaN的行删掉################################## 
nan_dropped = diabetes.dropna()

################################将diabetes中包含NaN的行删掉################################## 
print(nan_dropped.isnull().sum())
print("\nSize after dropping NaN rows",nan_dropped.shape)

Size before dropping NaN rows (768, 9)

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

Size after dropping NaN rows (336, 9)

### **Project2、数据分析的一系列问题**

In [16]:
vector = np.random.chisquare(1,500)
print(vector)
################################打印vector的均值################################## 
print("Mean",np.mean(vector))
################################打印vector的均值################################## 

print("SD",np.std(vector))
print("Range",max(vector)-min(vector))

[9.03844818e-01 2.08115665e+00 1.01715527e+00 4.77416263e-02
 8.61917844e+00 4.38649684e-01 6.58216126e-01 3.14494226e-01
 1.42333959e+00 4.40873368e-01 4.95570294e+00 1.72259455e+00
 8.24972514e-02 2.36771484e-01 1.40136776e-01 2.48572291e-01
 4.55280686e-04 7.01484981e-01 1.41463966e+00 1.21595357e+00
 1.93763691e+00 1.47182626e-03 2.44298541e+00 1.12309747e+00
 1.29706251e+00 8.44869502e-01 2.74774644e-01 7.29377297e-01
 6.86777889e-01 2.13328061e+00 2.07375026e-01 4.59626748e-01
 1.27887464e-02 1.05144001e+00 2.49315765e-01 1.71799404e+00
 1.47609962e-01 2.23617891e-01 1.27615455e-01 7.20243400e-01
 4.56702265e-01 9.39968929e-02 5.95897350e-01 4.19724091e-01
 1.82517612e+00 5.51451211e-02 2.43607613e+00 9.67528069e-01
 1.46684575e+00 1.49065246e-02 1.92794201e+00 1.80907563e+00
 3.36112747e-01 2.17007510e+00 3.64936898e-01 4.01005632e+00
 2.14376552e-01 5.85872769e-01 1.00117969e+00 1.69348715e-01
 6.54097151e-01 3.48507401e-01 8.57856439e-02 4.19644933e-03
 7.40666732e-03 1.41714212e-03 4.29783009e+00 8.23424950e-01
 3.77386417e-01 1.41000785e+00 1.03811680e-02 8.74275275e-01
 1.39805161e-01 4.23920501e-03 2.14208509e-02 3.94309391e-02
 1.81152977e+00 5.12771371e-01 8.22069732e-02 4.78652838e-01
 5.86403708e-02 2.96221584e-01 3.89414510e-03 1.70327472e-01
 3.47359866e-01 1.37417449e+00 2.40529516e-01 2.15436411e+00
 2.38679251e-01 3.41925685e-01 1.08977256e-03 1.23340374e-02
 3.18905701e-01 4.49291312e+00 3.85197582e+00 1.01380571e-02
 2.37821159e+00 1.37229729e+00 2.41019293e+00 1.27040721e+00
 9.59861963e-02 4.78937569e-01 2.15106296e+00 1.04108708e+00
 2.94766700e-01 2.10835648e-01 1.46808804e-01 1.93055172e-03
 2.84852436e-02 7.96067154e-01 2.21338468e-01 1.36666503e+00
 1.39948007e+00 2.39004506e+00 2.90539322e+00 9.82780036e-02
 3.79492394e-01 4.63077935e-02 1.05779241e+00 1.01196524e+00
 3.06859691e-03 1.20785259e+00 1.49224268e-01 1.28230582e-01
 9.64212603e-02 8.50682771e-02 1.71538805e+00 1.64560030e+00
 3.00256703e+00 1.35670326e+00 1.24360188e-02 9.30210279e-01
 2.68218284e-01 6.85658382e-01 1.72208126e+00 5.14765315e-03
 1.37780275e-03 6.23975027e-01 1.60011411e+00 1.20139768e+00
 1.06363627e+00 3.23978117e-01 1.52113217e+00 4.75265000e-01
 2.56178999e-03 3.81197088e-02 2.33053381e+00 9.29116208e-02
 1.20971809e+00 9.53986489e-02 1.13202911e+00 3.06328814e+00
 1.84984771e+00 2.48582482e+00 1.22279650e+00 4.72163360e+00
 4.19401414e-01 1.81236415e-01 9.92782097e-01 7.28662533e-01
 1.63709862e-02 4.42024642e+00 3.75660990e-01 9.25281145e-01
 5.04019541e-02 5.40292908e-01 7.76935796e-01 9.80471034e-02
 8.82901003e-02 2.99541373e+00 2.18344784e-01 2.48011817e+00
 2.55625687e+00 7.98462522e-01 6.43403047e+00 6.86906157e-01
 6.43292612e-03 1.79295352e-01 8.89643152e-01 4.41879686e-01
 1.31247683e-03 2.27371707e-02 2.20803298e+00 2.81339901e-01
 3.97717514e-01 1.10669816e-02 1.15506788e-02 1.90906152e-04
 2.11724695e-02 1.44760704e-01 4.92558991e+00 2.03101374e-01
 2.40753375e+00 8.27211278e-01 9.03016699e-01 9.17332658e-01
 2.58754475e-01 2.70570602e+00 4.54921092e-01 4.96172142e-01
 2.38902158e+00 7.75820428e+00 1.82937187e+00 3.98697480e-02
 6.10235663e-01 1.51551212e-02 1.16066280e+00 8.09363814e-01
 8.26366077e-03 1.18938646e-01 1.29762152e+00 6.25209648e-02
 5.90088983e-01 1.44493674e+00 1.65738921e+00 2.36852913e-02
 1.17128493e+00 4.77629090e-01 3.56387560e-01 5.46915877e-03
 2.50899650e+00 8.76717771e-01 9.35259786e-02 2.22906122e+00
 1.91526486e-01 3.71948972e-02 1.11806814e-02 3.90488481e-01
 9.07351462e-01 1.44019744e+00 2.48366398e+00 1.40211505e+00
 4.82683451e-01 2.10040787e+00 1.74247172e+00 1.66831040e+00
 3.20719239e-01 1.30647499e+00 1.19826823e+00 3.02105862e-01
 1.82319056e+00 3.71615555e+00 1.70958958e-01 1.35420872e+00
 1.50886043e-01 3.40493353e-02 3.78772269e-01 5.83027966e-01
 1.68880928e-01 1.02900320e-03 1.34860084e+00 7.02148629e-01
 2.85700700e+00 6.80939352e-02 1.35203556e-01 1.77972652e+00
 3.18676379e-02 7.38004885e-02 7.23590343e-01 1.59335360e-01
 3.10966998e-02 3.93746822e+00 1.39538185e-01 1.10152737e+00
 1.40103441e+00 6.16303620e-01 1.55329290e+00 4.25851929e-01
 1.99558505e-02 5.23012441e-01 1.79560696e+00 4.73865217e+00
 1.63941904e-02 6.36932458e-01 3.39358382e-01 5.59398556e+00
 5.85617129e-01 3.05017228e+00 1.12781155e-07 2.17278526e-02
 1.19425919e-02 1.24129516e-03 5.73187581e-01 2.46653878e-01
 2.81173680e+00 1.12978538e+00 2.12596798e+00 8.46678592e-01
 1.33173219e-02 9.97723384e-01 7.93942728e-02 4.64076220e-01
 6.36603220e-01 1.15576609e-01 1.89519089e+00 3.06270083e-03
 2.75378991e+00 2.84059059e+00 3.29185718e-02 3.09860219e-01
 1.83294786e-01 2.01128010e+00 2.67790205e+00 5.55107066e-02
 4.65235938e-01 5.11626651e+00 8.89877191e-01 2.98052856e-02
 1.38296322e+00 1.48010830e-01 7.20080236e-03 7.45722558e-01
 5.08397059e-01 6.18212474e-02 1.67865408e-01 1.10641584e-01
 5.44919255e-03 1.00958206e+00 7.17160080e-01 1.35126690e-01
 8.26084000e-04 3.35474488e-01 1.79778406e+00 1.79006445e+00
 1.71937195e+00 6.65631958e+00 5.33744979e-01 8.55130732e-01
 4.79680930e-01 2.43176614e-01 1.47630163e+00 9.48410233e-04
 3.58602609e-01 2.99763392e-02 6.45260142e-02 1.42805430e+00
 1.03976506e-01 1.27914289e-03 4.50862809e-01 1.35006444e+00
 5.34136276e-02 9.07454322e-01 3.33620249e+00 1.34858488e-01
 3.73555647e+00 3.33913802e-01 4.86619736e-01 9.20530385e-02
 1.67422453e-02 6.63383844e+00 3.52017191e-02 1.20693384e+00
 2.95295429e-02 4.25133649e-01 2.66362066e-03 1.96379892e-01
 3.12581188e+00 1.11904335e+00 1.25249323e-01 1.99933602e-02
 1.05879134e-01 4.45840215e-01 5.10322794e-01 2.60055550e+00
 1.32917646e+00 2.75751770e+00 1.44084263e-03 1.06095475e-01
 2.38524567e-02 4.33842920e-02 6.40812538e-01 1.88388452e+00
 4.63940669e-01 5.90820624e-01 2.50225342e-02 2.52089101e-02
 2.46161293e+00 7.70041126e+00 1.79871082e+00 6.69950482e-02
 5.66755671e-01 1.24775058e-01 2.45871301e+00 3.23850643e+00
 7.21120544e-01 8.19595154e-01 1.34838689e+00 3.80489708e-01
 6.99603628e-01 2.11202556e-01 2.50688885e-01 3.02977834e+00
 4.62258192e+00 1.15982972e+00 1.20491778e-03 1.31272724e+00
 1.81055045e-01 2.74637767e-01 3.10270823e-01 5.36075038e-01
 1.49718078e-01 3.21482767e+00 4.13174955e+00 1.08505503e-01
 2.38207037e+00 5.47957008e+00 1.72451662e+00 8.22686267e-01
 2.80699845e-01 8.41232127e-01 3.95213192e+00 5.73662692e-02
 1.08066406e-03 4.86436449e-01 5.89489408e-03 5.84752001e-03
 8.67463655e-02 7.56063014e-01 5.27474455e-02 1.72109239e+00
 4.07705581e-01 1.70011805e+00 3.29300333e-01 2.30847003e-01
 2.83297555e-02 9.47152928e-02 2.70281384e-02 4.13558631e-02
 4.97820836e+00 7.02855279e-02 3.49979131e-01 8.58154891e-01
 2.11499991e-02 2.54185759e+00 9.25837488e-01 9.92500531e-01
 3.16035717e+00 7.40821664e-02 5.14667612e-01 7.75250393e-01
 1.79446711e+00 5.77940449e-02 2.61859876e-01 1.15649053e+00
 2.51363022e+00 1.90642223e-02 1.98774330e-03 3.93575565e+00
 5.21694005e-03 3.97355690e-01 1.32380303e-01 3.69361174e-01
 6.61872472e+00 1.58652252e-01 8.32264242e-01 9.84254678e-03
 6.84559373e-01 2.51947380e-01 8.70827269e-01 3.46619564e-02
 1.91470357e+00 4.70694529e-02 1.14450348e+00 4.90140437e-01
 4.43646682e-01 4.22202915e-01 8.42852313e-01 5.45294813e-03
 2.89750326e-03 3.20968427e-02 5.21242405e-01 1.57654295e-02
 3.32312242e-01 4.04931790e-01 9.23850699e-02 4.92873588e-01
 8.12872580e-02 4.91539361e+00 3.47141897e-01 2.82833272e-01
 2.93313636e+00 2.11911791e+00 2.56869786e+00 1.29849472e+00
 7.29305857e-02 1.75820051e+00 3.59492238e-01 1.99112439e+00
 7.06252033e-01 6.91883291e-01 2.34408656e-01 3.90325792e+00
 1.83237760e+00 4.32723780e-03 8.99336194e-02 3.53886767e-02
 2.01317260e-01 6.78538994e-03 1.60736075e+00 3.73437814e+00]
Mean 1.0152258782205392
SD 1.344397892954187
Range 8.619178331135986

### Reshape

In [17]:
vector.shape

(500,)

In [18]:
################################将一维向量vector转成大小为500*1的二维向量并赋值给row_vector################################## 
row_vector = vector.reshape(-1,1)
################################将一维向量vector转成大小为500*1的二维向量并赋值给row_vector################################## 
row_vector.shape
print(row_vector)

[[9.03844818e-01]
 [2.08115665e+00]
 [1.01715527e+00]
 [4.77416263e-02]
 [8.61917844e+00]
 [4.38649684e-01]
 [6.58216126e-01]
 [3.14494226e-01]
 [1.42333959e+00]
 [4.40873368e-01]
 [4.95570294e+00]
 [1.72259455e+00]
 [8.24972514e-02]
 [2.36771484e-01]
 [1.40136776e-01]
 [2.48572291e-01]
 [4.55280686e-04]
 [7.01484981e-01]
 [1.41463966e+00]
 [1.21595357e+00]
 [1.93763691e+00]
 [1.47182626e-03]
 [2.44298541e+00]
 [1.12309747e+00]
 [1.29706251e+00]
 [8.44869502e-01]
 [2.74774644e-01]
 [7.29377297e-01]
 [6.86777889e-01]
 [2.13328061e+00]
 [2.07375026e-01]
 [4.59626748e-01]
 [1.27887464e-02]
 [1.05144001e+00]
 [2.49315765e-01]
 [1.71799404e+00]
 [1.47609962e-01]
 [2.23617891e-01]
 [1.27615455e-01]
 [7.20243400e-01]
 [4.56702265e-01]
 [9.39968929e-02]
 [5.95897350e-01]
 [4.19724091e-01]
 [1.82517612e+00]
 [5.51451211e-02]
 [2.43607613e+00]
 [9.67528069e-01]
 [1.46684575e+00]
 [1.49065246e-02]
 [1.92794201e+00]
 [1.80907563e+00]
 [3.36112747e-01]
 [2.17007510e+00]
 [3.64936898e-01]
 [4.01005632e+00]
 [2.14376552e-01]
 [5.85872769e-01]
 [1.00117969e+00]
 [1.69348715e-01]
 [6.54097151e-01]
 [3.48507401e-01]
 [8.57856439e-02]
 [4.19644933e-03]
 [7.40666732e-03]
 [1.41714212e-03]
 [4.29783009e+00]
 [8.23424950e-01]
 [3.77386417e-01]
 [1.41000785e+00]
 [1.03811680e-02]
 [8.74275275e-01]
 [1.39805161e-01]
 [4.23920501e-03]
 [2.14208509e-02]
 [3.94309391e-02]
 [1.81152977e+00]
 [5.12771371e-01]
 [8.22069732e-02]
 [4.78652838e-01]
 [5.86403708e-02]
 [2.96221584e-01]
 [3.89414510e-03]
 [1.70327472e-01]
 [3.47359866e-01]
 [1.37417449e+00]
 [2.40529516e-01]
 [2.15436411e+00]
 [2.38679251e-01]
 [3.41925685e-01]
 [1.08977256e-03]
 [1.23340374e-02]
 [3.18905701e-01]
 [4.49291312e+00]
 [3.85197582e+00]
 [1.01380571e-02]
 [2.37821159e+00]
 [1.37229729e+00]
 [2.41019293e+00]
 [1.27040721e+00]
 [9.59861963e-02]
 [4.78937569e-01]
 [2.15106296e+00]
 [1.04108708e+00]
 [2.94766700e-01]
 [2.10835648e-01]
 [1.46808804e-01]
 [1.93055172e-03]
 [2.84852436e-02]
 [7.96067154e-01]
 [2.21338468e-01]
 [1.36666503e+00]
 [1.39948007e+00]
 [2.39004506e+00]
 [2.90539322e+00]
 [9.82780036e-02]
 [3.79492394e-01]
 [4.63077935e-02]
 [1.05779241e+00]
 [1.01196524e+00]
 [3.06859691e-03]
 [1.20785259e+00]
 [1.49224268e-01]
 [1.28230582e-01]
 [9.64212603e-02]
 [8.50682771e-02]
 [1.71538805e+00]
 [1.64560030e+00]
 [3.00256703e+00]
 [1.35670326e+00]
 [1.24360188e-02]
 [9.30210279e-01]
 [2.68218284e-01]
 [6.85658382e-01]
 [1.72208126e+00]
 [5.14765315e-03]
 [1.37780275e-03]
 [6.23975027e-01]
 [1.60011411e+00]
 [1.20139768e+00]
 [1.06363627e+00]
 [3.23978117e-01]
 [1.52113217e+00]
 [4.75265000e-01]
 [2.56178999e-03]
 [3.81197088e-02]
 [2.33053381e+00]
 [9.29116208e-02]
 [1.20971809e+00]
 [9.53986489e-02]
 [1.13202911e+00]
 [3.06328814e+00]
 [1.84984771e+00]
 [2.48582482e+00]
 [1.22279650e+00]
 [4.72163360e+00]
 [4.19401414e-01]
 [1.81236415e-01]
 [9.92782097e-01]
 [7.28662533e-01]
 [1.63709862e-02]
 [4.42024642e+00]
 [3.75660990e-01]
 [9.25281145e-01]
 [5.04019541e-02]
 [5.40292908e-01]
 [7.76935796e-01]
 [9.80471034e-02]
 [8.82901003e-02]
 [2.99541373e+00]
 [2.18344784e-01]
 [2.48011817e+00]
 [2.55625687e+00]
 [7.98462522e-01]
 [6.43403047e+00]
 [6.86906157e-01]
 [6.43292612e-03]
 [1.79295352e-01]
 [8.89643152e-01]
 [4.41879686e-01]
 [1.31247683e-03]
 [2.27371707e-02]
 [2.20803298e+00]
 [2.81339901e-01]
 [3.97717514e-01]
 [1.10669816e-02]
 [1.15506788e-02]
 [1.90906152e-04]
 [2.11724695e-02]
 [1.44760704e-01]
 [4.92558991e+00]
 [2.03101374e-01]
 [2.40753375e+00]
 [8.27211278e-01]
 [9.03016699e-01]
 [9.17332658e-01]
 [2.58754475e-01]
 [2.70570602e+00]
 [4.54921092e-01]
 [4.96172142e-01]
 [2.38902158e+00]
 [7.75820428e+00]
 [1.82937187e+00]
 [3.98697480e-02]
 [6.10235663e-01]
 [1.51551212e-02]
 [1.16066280e+00]
 [8.09363814e-01]
 [8.26366077e-03]
 [1.18938646e-01]
 [1.29762152e+00]
 [6.25209648e-02]
 [5.90088983e-01]
 [1.44493674e+00]
 [1.65738921e+00]
 [2.36852913e-02]
 [1.17128493e+00]
 [4.77629090e-01]
 [3.56387560e-01]
 [5.46915877e-03]
 [2.50899650e+00]
 [8.76717771e-01]
 [9.35259786e-02]
 [2.22906122e+00]
 [1.91526486e-01]
 [3.71948972e-02]
 [1.11806814e-02]
 [3.90488481e-01]
 [9.07351462e-01]
 [1.44019744e+00]
 [2.48366398e+00]
 [1.40211505e+00]
 [4.82683451e-01]
 [2.10040787e+00]
 [1.74247172e+00]
 [1.66831040e+00]
 [3.20719239e-01]
 [1.30647499e+00]
 [1.19826823e+00]
 [3.02105862e-01]
 [1.82319056e+00]
 [3.71615555e+00]
 [1.70958958e-01]
 [1.35420872e+00]
 [1.50886043e-01]
 [3.40493353e-02]
 [3.78772269e-01]
 [5.83027966e-01]
 [1.68880928e-01]
 [1.02900320e-03]
 [1.34860084e+00]
 [7.02148629e-01]
 [2.85700700e+00]
 [6.80939352e-02]
 [1.35203556e-01]
 [1.77972652e+00]
 [3.18676379e-02]
 [7.38004885e-02]
 [7.23590343e-01]
 [1.59335360e-01]
 [3.10966998e-02]
 [3.93746822e+00]
 [1.39538185e-01]
 [1.10152737e+00]
 [1.40103441e+00]
 [6.16303620e-01]
 [1.55329290e+00]
 [4.25851929e-01]
 [1.99558505e-02]
 [5.23012441e-01]
 [1.79560696e+00]
 [4.73865217e+00]
 [1.63941904e-02]
 [6.36932458e-01]
 [3.39358382e-01]
 [5.59398556e+00]
 [5.85617129e-01]
 [3.05017228e+00]
 [1.12781155e-07]
 [2.17278526e-02]
 [1.19425919e-02]
 [1.24129516e-03]
 [5.73187581e-01]
 [2.46653878e-01]
 [2.81173680e+00]
 [1.12978538e+00]
 [2.12596798e+00]
 [8.46678592e-01]
 [1.33173219e-02]
 [9.97723384e-01]
 [7.93942728e-02]
 [4.64076220e-01]
 [6.36603220e-01]
 [1.15576609e-01]
 [1.89519089e+00]
 [3.06270083e-03]
 [2.75378991e+00]
 [2.84059059e+00]
 [3.29185718e-02]
 [3.09860219e-01]
 [1.83294786e-01]
 [2.01128010e+00]
 [2.67790205e+00]
 [5.55107066e-02]
 [4.65235938e-01]
 [5.11626651e+00]
 [8.89877191e-01]
 [2.98052856e-02]
 [1.38296322e+00]
 [1.48010830e-01]
 [7.20080236e-03]
 [7.45722558e-01]
 [5.08397059e-01]
 [6.18212474e-02]
 [1.67865408e-01]
 [1.10641584e-01]
 [5.44919255e-03]
 [1.00958206e+00]
 [7.17160080e-01]
 [1.35126690e-01]
 [8.26084000e-04]
 [3.35474488e-01]
 [1.79778406e+00]
 [1.79006445e+00]
 [1.71937195e+00]
 [6.65631958e+00]
 [5.33744979e-01]
 [8.55130732e-01]
 [4.79680930e-01]
 [2.43176614e-01]
 [1.47630163e+00]
 [9.48410233e-04]
 [3.58602609e-01]
 [2.99763392e-02]
 [6.45260142e-02]
 [1.42805430e+00]
 [1.03976506e-01]
 [1.27914289e-03]
 [4.50862809e-01]
 [1.35006444e+00]
 [5.34136276e-02]
 [9.07454322e-01]
 [3.33620249e+00]
 [1.34858488e-01]
 [3.73555647e+00]
 [3.33913802e-01]
 [4.86619736e-01]
 [9.20530385e-02]
 [1.67422453e-02]
 [6.63383844e+00]
 [3.52017191e-02]
 [1.20693384e+00]
 [2.95295429e-02]
 [4.25133649e-01]
 [2.66362066e-03]
 [1.96379892e-01]
 [3.12581188e+00]
 [1.11904335e+00]
 [1.25249323e-01]
 [1.99933602e-02]
 [1.05879134e-01]
 [4.45840215e-01]
 [5.10322794e-01]
 [2.60055550e+00]
 [1.32917646e+00]
 [2.75751770e+00]
 [1.44084263e-03]
 [1.06095475e-01]
 [2.38524567e-02]
 [4.33842920e-02]
 [6.40812538e-01]
 [1.88388452e+00]
 [4.63940669e-01]
 [5.90820624e-01]
 [2.50225342e-02]
 [2.52089101e-02]
 [2.46161293e+00]
 [7.70041126e+00]
 [1.79871082e+00]
 [6.69950482e-02]
 [5.66755671e-01]
 [1.24775058e-01]
 [2.45871301e+00]
 [3.23850643e+00]
 [7.21120544e-01]
 [8.19595154e-01]
 [1.34838689e+00]
 [3.80489708e-01]
 [6.99603628e-01]
 [2.11202556e-01]
 [2.50688885e-01]
 [3.02977834e+00]
 [4.62258192e+00]
 [1.15982972e+00]
 [1.20491778e-03]
 [1.31272724e+00]
 [1.81055045e-01]
 [2.74637767e-01]
 [3.10270823e-01]
 [5.36075038e-01]
 [1.49718078e-01]
 [3.21482767e+00]
 [4.13174955e+00]
 [1.08505503e-01]
 [2.38207037e+00]
 [5.47957008e+00]
 [1.72451662e+00]
 [8.22686267e-01]
 [2.80699845e-01]
 [8.41232127e-01]
 [3.95213192e+00]
 [5.73662692e-02]
 [1.08066406e-03]
 [4.86436449e-01]
 [5.89489408e-03]
 [5.84752001e-03]
 [8.67463655e-02]
 [7.56063014e-01]
 [5.27474455e-02]
 [1.72109239e+00]
 [4.07705581e-01]
 [1.70011805e+00]
 [3.29300333e-01]
 [2.30847003e-01]
 [2.83297555e-02]
 [9.47152928e-02]
 [2.70281384e-02]
 [4.13558631e-02]
 [4.97820836e+00]
 [7.02855279e-02]
 [3.49979131e-01]
 [8.58154891e-01]
 [2.11499991e-02]
 [2.54185759e+00]
 [9.25837488e-01]
 [9.92500531e-01]
 [3.16035717e+00]
 [7.40821664e-02]
 [5.14667612e-01]
 [7.75250393e-01]
 [1.79446711e+00]
 [5.77940449e-02]
 [2.61859876e-01]
 [1.15649053e+00]
 [2.51363022e+00]
 [1.90642223e-02]
 [1.98774330e-03]
 [3.93575565e+00]
 [5.21694005e-03]
 [3.97355690e-01]
 [1.32380303e-01]
 [3.69361174e-01]
 [6.61872472e+00]
 [1.58652252e-01]
 [8.32264242e-01]
 [9.84254678e-03]
 [6.84559373e-01]
 [2.51947380e-01]
 [8.70827269e-01]
 [3.46619564e-02]
 [1.91470357e+00]
 [4.70694529e-02]
 [1.14450348e+00]
 [4.90140437e-01]
 [4.43646682e-01]
 [4.22202915e-01]
 [8.42852313e-01]
 [5.45294813e-03]
 [2.89750326e-03]
 [3.20968427e-02]
 [5.21242405e-01]
 [1.57654295e-02]
 [3.32312242e-01]
 [4.04931790e-01]
 [9.23850699e-02]
 [4.92873588e-01]
 [8.12872580e-02]
 [4.91539361e+00]
 [3.47141897e-01]
 [2.82833272e-01]
 [2.93313636e+00]
 [2.11911791e+00]
 [2.56869786e+00]
 [1.29849472e+00]
 [7.29305857e-02]
 [1.75820051e+00]
 [3.59492238e-01]
 [1.99112439e+00]
 [7.06252033e-01]
 [6.91883291e-01]
 [2.34408656e-01]
 [3.90325792e+00]
 [1.83237760e+00]
 [4.32723780e-03]
 [8.99336194e-02]
 [3.53886767e-02]
 [2.01317260e-01]
 [6.78538994e-03]
 [1.60736075e+00]
 [3.73437814e+00]]

In [19]:
col_vector = vector.reshape(1,-1)
col_vector.shape

(1, 500)

In [20]:
################################将一维向量vector转成大小为10*50的二维向量并赋值给maxtrix################################## 
matrix = vector.reshape(10,50)
################################将一维向量vector转成大小为10*50的二维向量并赋值给maxtrix################################## 
matrix.shape
print(matrix)

[[9.03844818e-01 2.08115665e+00 1.01715527e+00 4.77416263e-02
  8.61917844e+00 4.38649684e-01 6.58216126e-01 3.14494226e-01
  1.42333959e+00 4.40873368e-01 4.95570294e+00 1.72259455e+00
  8.24972514e-02 2.36771484e-01 1.40136776e-01 2.48572291e-01
  4.55280686e-04 7.01484981e-01 1.41463966e+00 1.21595357e+00
  1.93763691e+00 1.47182626e-03 2.44298541e+00 1.12309747e+00
  1.29706251e+00 8.44869502e-01 2.74774644e-01 7.29377297e-01
  6.86777889e-01 2.13328061e+00 2.07375026e-01 4.59626748e-01
  1.27887464e-02 1.05144001e+00 2.49315765e-01 1.71799404e+00
  1.47609962e-01 2.23617891e-01 1.27615455e-01 7.20243400e-01
  4.56702265e-01 9.39968929e-02 5.95897350e-01 4.19724091e-01
  1.82517612e+00 5.51451211e-02 2.43607613e+00 9.67528069e-01
  1.46684575e+00 1.49065246e-02]
 [1.92794201e+00 1.80907563e+00 3.36112747e-01 2.17007510e+00
  3.64936898e-01 4.01005632e+00 2.14376552e-01 5.85872769e-01
  1.00117969e+00 1.69348715e-01 6.54097151e-01 3.48507401e-01
  8.57856439e-02 4.19644933e-03 7.40666732e-03 1.41714212e-03
  4.29783009e+00 8.23424950e-01 3.77386417e-01 1.41000785e+00
  1.03811680e-02 8.74275275e-01 1.39805161e-01 4.23920501e-03
  2.14208509e-02 3.94309391e-02 1.81152977e+00 5.12771371e-01
  8.22069732e-02 4.78652838e-01 5.86403708e-02 2.96221584e-01
  3.89414510e-03 1.70327472e-01 3.47359866e-01 1.37417449e+00
  2.40529516e-01 2.15436411e+00 2.38679251e-01 3.41925685e-01
  1.08977256e-03 1.23340374e-02 3.18905701e-01 4.49291312e+00
  3.85197582e+00 1.01380571e-02 2.37821159e+00 1.37229729e+00
  2.41019293e+00 1.27040721e+00]
 [9.59861963e-02 4.78937569e-01 2.15106296e+00 1.04108708e+00
  2.94766700e-01 2.10835648e-01 1.46808804e-01 1.93055172e-03
  2.84852436e-02 7.96067154e-01 2.21338468e-01 1.36666503e+00
  1.39948007e+00 2.39004506e+00 2.90539322e+00 9.82780036e-02
  3.79492394e-01 4.63077935e-02 1.05779241e+00 1.01196524e+00
  3.06859691e-03 1.20785259e+00 1.49224268e-01 1.28230582e-01
  9.64212603e-02 8.50682771e-02 1.71538805e+00 1.64560030e+00
  3.00256703e+00 1.35670326e+00 1.24360188e-02 9.30210279e-01
  2.68218284e-01 6.85658382e-01 1.72208126e+00 5.14765315e-03
  1.37780275e-03 6.23975027e-01 1.60011411e+00 1.20139768e+00
  1.06363627e+00 3.23978117e-01 1.52113217e+00 4.75265000e-01
  2.56178999e-03 3.81197088e-02 2.33053381e+00 9.29116208e-02
  1.20971809e+00 9.53986489e-02]
 [1.13202911e+00 3.06328814e+00 1.84984771e+00 2.48582482e+00
  1.22279650e+00 4.72163360e+00 4.19401414e-01 1.81236415e-01
  9.92782097e-01 7.28662533e-01 1.63709862e-02 4.42024642e+00
  3.75660990e-01 9.25281145e-01 5.04019541e-02 5.40292908e-01
  7.76935796e-01 9.80471034e-02 8.82901003e-02 2.99541373e+00
  2.18344784e-01 2.48011817e+00 2.55625687e+00 7.98462522e-01
  6.43403047e+00 6.86906157e-01 6.43292612e-03 1.79295352e-01
  8.89643152e-01 4.41879686e-01 1.31247683e-03 2.27371707e-02
  2.20803298e+00 2.81339901e-01 3.97717514e-01 1.10669816e-02
  1.15506788e-02 1.90906152e-04 2.11724695e-02 1.44760704e-01
  4.92558991e+00 2.03101374e-01 2.40753375e+00 8.27211278e-01
  9.03016699e-01 9.17332658e-01 2.58754475e-01 2.70570602e+00
  4.54921092e-01 4.96172142e-01]
 [2.38902158e+00 7.75820428e+00 1.82937187e+00 3.98697480e-02
  6.10235663e-01 1.51551212e-02 1.16066280e+00 8.09363814e-01
  8.26366077e-03 1.18938646e-01 1.29762152e+00 6.25209648e-02
  5.90088983e-01 1.44493674e+00 1.65738921e+00 2.36852913e-02
  1.17128493e+00 4.77629090e-01 3.56387560e-01 5.46915877e-03
  2.50899650e+00 8.76717771e-01 9.35259786e-02 2.22906122e+00
  1.91526486e-01 3.71948972e-02 1.11806814e-02 3.90488481e-01
  9.07351462e-01 1.44019744e+00 2.48366398e+00 1.40211505e+00
  4.82683451e-01 2.10040787e+00 1.74247172e+00 1.66831040e+00
  3.20719239e-01 1.30647499e+00 1.19826823e+00 3.02105862e-01
  1.82319056e+00 3.71615555e+00 1.70958958e-01 1.35420872e+00
  1.50886043e-01 3.40493353e-02 3.78772269e-01 5.83027966e-01
  1.68880928e-01 1.02900320e-03]
 [1.34860084e+00 7.02148629e-01 2.85700700e+00 6.80939352e-02
  1.35203556e-01 1.77972652e+00 3.18676379e-02 7.38004885e-02
  7.23590343e-01 1.59335360e-01 3.10966998e-02 3.93746822e+00
  1.39538185e-01 1.10152737e+00 1.40103441e+00 6.16303620e-01
  1.55329290e+00 4.25851929e-01 1.99558505e-02 5.23012441e-01
  1.79560696e+00 4.73865217e+00 1.63941904e-02 6.36932458e-01
  3.39358382e-01 5.59398556e+00 5.85617129e-01 3.05017228e+00
  1.12781155e-07 2.17278526e-02 1.19425919e-02 1.24129516e-03
  5.73187581e-01 2.46653878e-01 2.81173680e+00 1.12978538e+00
  2.12596798e+00 8.46678592e-01 1.33173219e-02 9.97723384e-01
  7.93942728e-02 4.64076220e-01 6.36603220e-01 1.15576609e-01
  1.89519089e+00 3.06270083e-03 2.75378991e+00 2.84059059e+00
  3.29185718e-02 3.09860219e-01]
 [1.83294786e-01 2.01128010e+00 2.67790205e+00 5.55107066e-02
  4.65235938e-01 5.11626651e+00 8.89877191e-01 2.98052856e-02
  1.38296322e+00 1.48010830e-01 7.20080236e-03 7.45722558e-01
  5.08397059e-01 6.18212474e-02 1.67865408e-01 1.10641584e-01
  5.44919255e-03 1.00958206e+00 7.17160080e-01 1.35126690e-01
  8.26084000e-04 3.35474488e-01 1.79778406e+00 1.79006445e+00
  1.71937195e+00 6.65631958e+00 5.33744979e-01 8.55130732e-01
  4.79680930e-01 2.43176614e-01 1.47630163e+00 9.48410233e-04
  3.58602609e-01 2.99763392e-02 6.45260142e-02 1.42805430e+00
  1.03976506e-01 1.27914289e-03 4.50862809e-01 1.35006444e+00
  5.34136276e-02 9.07454322e-01 3.33620249e+00 1.34858488e-01
  3.73555647e+00 3.33913802e-01 4.86619736e-01 9.20530385e-02
  1.67422453e-02 6.63383844e+00]
 [3.52017191e-02 1.20693384e+00 2.95295429e-02 4.25133649e-01
  2.66362066e-03 1.96379892e-01 3.12581188e+00 1.11904335e+00
  1.25249323e-01 1.99933602e-02 1.05879134e-01 4.45840215e-01
  5.10322794e-01 2.60055550e+00 1.32917646e+00 2.75751770e+00
  1.44084263e-03 1.06095475e-01 2.38524567e-02 4.33842920e-02
  6.40812538e-01 1.88388452e+00 4.63940669e-01 5.90820624e-01
  2.50225342e-02 2.52089101e-02 2.46161293e+00 7.70041126e+00
  1.79871082e+00 6.69950482e-02 5.66755671e-01 1.24775058e-01
  2.45871301e+00 3.23850643e+00 7.21120544e-01 8.19595154e-01
  1.34838689e+00 3.80489708e-01 6.99603628e-01 2.11202556e-01
  2.50688885e-01 3.02977834e+00 4.62258192e+00 1.15982972e+00
  1.20491778e-03 1.31272724e+00 1.81055045e-01 2.74637767e-01
  3.10270823e-01 5.36075038e-01]
 [1.49718078e-01 3.21482767e+00 4.13174955e+00 1.08505503e-01
  2.38207037e+00 5.47957008e+00 1.72451662e+00 8.22686267e-01
  2.80699845e-01 8.41232127e-01 3.95213192e+00 5.73662692e-02
  1.08066406e-03 4.86436449e-01 5.89489408e-03 5.84752001e-03
  8.67463655e-02 7.56063014e-01 5.27474455e-02 1.72109239e+00
  4.07705581e-01 1.70011805e+00 3.29300333e-01 2.30847003e-01
  2.83297555e-02 9.47152928e-02 2.70281384e-02 4.13558631e-02
  4.97820836e+00 7.02855279e-02 3.49979131e-01 8.58154891e-01
  2.11499991e-02 2.54185759e+00 9.25837488e-01 9.92500531e-01
  3.16035717e+00 7.40821664e-02 5.14667612e-01 7.75250393e-01
  1.79446711e+00 5.77940449e-02 2.61859876e-01 1.15649053e+00
  2.51363022e+00 1.90642223e-02 1.98774330e-03 3.93575565e+00
  5.21694005e-03 3.97355690e-01]
 [1.32380303e-01 3.69361174e-01 6.61872472e+00 1.58652252e-01
  8.32264242e-01 9.84254678e-03 6.84559373e-01 2.51947380e-01
  8.70827269e-01 3.46619564e-02 1.91470357e+00 4.70694529e-02
  1.14450348e+00 4.90140437e-01 4.43646682e-01 4.22202915e-01
  8.42852313e-01 5.45294813e-03 2.89750326e-03 3.20968427e-02
  5.21242405e-01 1.57654295e-02 3.32312242e-01 4.04931790e-01
  9.23850699e-02 4.92873588e-01 8.12872580e-02 4.91539361e+00
  3.47141897e-01 2.82833272e-01 2.93313636e+00 2.11911791e+00
  2.56869786e+00 1.29849472e+00 7.29305857e-02 1.75820051e+00
  3.59492238e-01 1.99112439e+00 7.06252033e-01 6.91883291e-01
  2.34408656e-01 3.90325792e+00 1.83237760e+00 4.32723780e-03
  8.99336194e-02 3.53886767e-02 2.01317260e-01 6.78538994e-03
  1.60736075e+00 3.73437814e+00]]

### Pivot Table

In [21]:
#Determine pivot table
df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
                       "bar", "bar", "bar", "bar"],
                    "B": ["one", "one", "one", "two", "two",
                          "one", "one", "two", "two"],
                    "C": ["small", "large", "large", "small",
                          "small", "large", "small", "small",
                          "large"],
                    "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
                    "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]})

In [22]:
df.head(9)

     A    B      C  D  E
0  foo  one  small  1  2
1  foo  one  large  2  4
2  foo  one  large  2  5
3  foo  two  small  3  5
4  foo  two  small  3  6
5  bar  one  large  4  6
6  bar  one  small  5  8
7  bar  two  small  6  9
8  bar  two  large  7  9

In [23]:
###################################想办法生成以下表格，行为A、B，列为C###################################
table = pivot_table(df, values='D', index=['A', 'B'],
                  columns=['C'], aggfunc=np.sum)

###################################想办法生成以下表格，行为A、B，列为C###################################
table

C        large  small
A   B
bar one    4.0    5.0
    two    7.0    6.0
foo one    4.0    1.0
    two    NaN    6.0

### Merging dataframes

In [24]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                       index=[0, 1, 2, 3])
    

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                       index=[4, 5, 6, 7])
    

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                       'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                       index=[8, 9, 10, 11])
    
###################################将df1,df2,df3按行拼接到一起，并赋给result###################################
frames = [df1, df2, df3]

result = pd.concat(frames)

###################################将df1,df2,df3按行拼接到一起，并赋给result####################################

print(result)

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11